//! Build-time generation of the canonical opcode enum.
//!
//! Reads `configs/opcodes/*.json`, takes the union of all opcode names across
//! Python versions, filters out runtime-only specializations (which never
//! appear in .pyc files), and emits `OUT_DIR/opnames.inc`:
//!
//! ```ignore
//! pub enum Op { ... }
//! impl Op { pub fn from_name(name: &str) -> Option<Op> { ... } }
//! ```

use std::collections::BTreeSet;
use std::io::Write;

/// Name prefixes that only exist as runtime specializations / instrumentation
/// and never appear in serialized bytecode.
const EXCLUDE_PREFIXES: &[&str] = &[
    "INSTRUMENTED_",
    "TRACE_",
    "ENTER_EXECUTOR",
    "RESERVED",
    "EXIT_INIT_CHECK",
];

/// Exact names excluded: adaptive specializations, JIT variants, and Graal/
/// RustPython-only helpers that the decompiler treats as their base opcode.
fn is_excluded(name: &str) -> bool {
    if EXCLUDE_PREFIXES.iter().any(|p| name.starts_with(p)) {
        return true;
    }
    if name.ends_with("_JIT") {
        return true;
    }
    // Specialized forms keep a base prefix plus a specialization suffix.
    const SPECIALIZED_BASES: &[&str] = &[
        "BINARY_OP_",
        "BINARY_SUBSCR_",
        "CALL_BOUND_METHOD",
        "CALL_BUILTIN",
        "CALL_NON_PY",
        "CALL_PY_",
        "CALL_LEN",
        "CALL_STR_",
        "CALL_TUPLE_",
        "CALL_TYPE_",
        "CALL_ISINSTANCE",
        "CALL_ALLOC_AND_ENTER_INIT",
        "CALL_EX_PY",
        "CALL_EX_NON_PY",
        "CALL_KW_BOUND_METHOD",
        "CALL_KW_NON_PY",
        "CALL_KW_PY",
        "CALL_METHOD_DESCRIPTOR",
        "CALL_FUNCTION_EX_PY",
        "CALL_FUNCTION_EX_NON_PY",
        "COMPARE_OP_",
        "CONTAINS_OP_",
        "FOR_ITER_",
        "LOAD_ATTR_",
        "LOAD_GLOBAL_",
        "LOAD_SUPER_ATTR_",
        "LOAD_SUPER_METHOD",
        "LOAD_ZERO_SUPER",
        "STORE_ATTR_",
        "STORE_SUBSCR_",
        "TO_BOOL_",
        "UNPACK_SEQUENCE_",
        "SEND_GEN",
        "SEND_ASYNC_GEN",
        "SEND_VIRTUAL",
        "GET_ITER_SELF",
        "GET_ITER_VIRTUAL",
        "JUMP_BACKWARD_NO_JIT",
        "POP_JUMP_IF_ALWAYS_TRUE",
        "BUILD_INTERPOLATION",
        "BUILD_TEMPLATE",
    ];
    // Keep real opcodes that would otherwise be caught by the prefix rules.
    const KEEP: &[&str] = &[
        "CALL_FUNCTION",
        "CALL_FUNCTION_KW",
        "CALL_FUNCTION_VAR",
        "CALL_FUNCTION_VAR_KW",
        "CALL_FUNCTION_EX",
        "CALL_METHOD",
        "CALL_FINALLY",
        "CALL_KW",
        "CALL",
        "FOR_ITER",
        "GET_ITER",
        "GET_AITER",
        "GET_ANEXT",
        "GET_AWAITABLE",
        "GET_YIELD_FROM_ITER",
        "GET_LEN",
        "SEND",
        "JUMP_BACKWARD",
        "JUMP_BACKWARD_NO_INTERRUPT",
        "RESUME",
        "TO_BOOL",
        "COMPARE_OP",
        "CONTAINS_OP",
        "BINARY_OP",
        "BINARY_SUBSCR",
        "UNPACK_SEQUENCE",
        "STORE_SUBSCR",
        "STORE_ATTR",
        "LOAD_ATTR",
        "LOAD_GLOBAL",
        "LOAD_SUPER_ATTR",
    ];
    if KEEP.contains(&name) {
        return false;
    }
    SPECIALIZED_BASES.iter().any(|p| name.starts_with(p))
}

fn main() {
    println!("cargo:rerun-if-changed=configs/opcodes");
    println!("cargo:rerun-if-changed=build.rs");

    let mut names = BTreeSet::new();
    for entry in std::fs::read_dir("configs/opcodes").expect("configs/opcodes exists") {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }
        let text = std::fs::read_to_string(&path).expect("read config");
        let value: serde_json::Value = serde_json::from_str(&text).expect("parse config");
        let opmap = value.get("opmap").expect("opmap").as_object().expect("obj");
        for name in opmap.keys() {
            if !is_excluded(name) {
                names.insert(name.clone());
            }
        }
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("opnames.inc");
    let mut f = std::fs::File::create(path).expect("create opnames.inc");

    writeln!(f, "// Generated by build.rs from configs/opcodes/*.json — do not edit.").unwrap();
    writeln!(f, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
    writeln!(f, "pub enum Op {{").unwrap();
    writeln!(f, "    Unknown,").unwrap();
    for n in &names {
        writeln!(f, "    {n},").unwrap();
    }
    writeln!(f, "}}").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "impl Op {{").unwrap();
    writeln!(f, "    /// Map a per-version opcode name to the canonical enum.").unwrap();
    writeln!(f, "    pub fn from_name(name: &str) -> Op {{").unwrap();
    writeln!(f, "        match name {{").unwrap();
    for n in &names {
        writeln!(f, "            \"{n}\" => Op::{n},").unwrap();
    }
    writeln!(f, "            _ => Op::Unknown,").unwrap();
    writeln!(f, "        }}").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "    /// Canonical name for display (Unknown opcodes use the raw name).").unwrap();
    writeln!(f, "    pub fn name_str(self) -> &'static str {{").unwrap();
    writeln!(f, "        match self {{").unwrap();
    writeln!(f, "            Op::Unknown => \"<unknown>\",").unwrap();
    for n in &names {
        writeln!(f, "            Op::{n} => \"{n}\",").unwrap();
    }
    writeln!(f, "        }}").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "}}").unwrap();

    eprintln!("generated {} canonical opcodes", names.len());
}
